// Package contract defines all backend interfaces that providers must implement.
// These interfaces are separated into their own package to avoid circular dependencies
// between backend services (orchestrator, processor) and provider implementations.
// This package serves as the single source of truth for all backend provider dependencies.
package contract

import (
	"context"
	"encoding/json"
	"log/slog"
	"time"

	"runvoy/internal/api"
)

// TaskManager abstracts provider-specific task execution (e.g., AWS ECS, GCP Cloud Run, Azure Container Instances).
// This interface handles the core responsibility of running and managing task lifecycles.
type TaskManager interface {
	// StartTask triggers an execution on the underlying platform and returns
	// a stable executionID and the task creation timestamp.
	// The createdAt timestamp comes from the provider (e.g., ECS CreatedAt) when available.
	StartTask(
		ctx context.Context,
		userEmail string,
		req *api.ExecutionRequest) (executionID string, createdAt *time.Time, err error)
	// KillTask terminates a running task identified by executionID.
	// Returns an error if the task is already terminated or cannot be terminated.
	KillTask(ctx context.Context, executionID string) error
}

// ImageRegistry abstracts provider-specific image management.
// This interface handles image registration, configuration, and lifecycle management.
type ImageRegistry interface {
	// RegisterImage registers a Docker image as a task definition in the execution platform.
	// isDefault: if true, explicitly set as default.
	// taskRoleName: optional custom task role name (if nil, uses default from config).
	// taskExecutionRoleName: optional custom task execution role name (if nil, uses default from config).
	// cpu: optional CPU value (e.g., 256, 1024). Defaults to 256 if nil.
	// memory: optional Memory value in MB (e.g., 512, 2048). Defaults to 512 if nil.
	// runtimePlatform: optional runtime platform (e.g., "Linux/ARM64", "Linux/X86_64"). Defaults to "Linux/ARM64" if nil.
	// createdBy: email of the user registering the image.
	RegisterImage(
		ctx context.Context,
		image string,
		isDefault *bool,
		taskRoleName, taskExecutionRoleName *string,
		cpu, memory *int,
		runtimePlatform *string,
		createdBy string,
	) error
	// ListImages lists all registered Docker images.
	ListImages(ctx context.Context) ([]api.ImageInfo, error)

	// GetImage retrieves a single Docker image by ID or name.
	// Accepts either an ImageID (e.g., "alpine:latest-a1b2c3d4") or an image name (e.g., "alpine:latest").
	GetImage(ctx context.Context, image string) (*api.ImageInfo, error)

	// RemoveImage removes a Docker image and deregisters its task definitions.
	RemoveImage(ctx context.Context, image string) error
}

// LogManager abstracts provider-specific execution log retrieval.
// This interface handles fetching logs from user task executions.
type LogManager interface {
	// FetchLogsByExecutionID retrieves execution logs for a specific execution.
	// Returns logs generated by the user's command execution in containers.
	// Returns empty slice if logs are not available or not supported by the provider.
	FetchLogsByExecutionID(ctx context.Context, executionID string) ([]api.LogEvent, error)
}

// ObservabilityManager provides access to backend infrastructure logs and metrics.
// This interface is for platform debugging and observability, separate from user execution logs.
type ObservabilityManager interface {
	// FetchBackendLogs retrieves logs from the backend services for the provided requestID.
	// Returns logs from the backend services for debugging and tracing.
	FetchBackendLogs(ctx context.Context, requestID string) ([]api.LogEvent, error)
}

// WebSocketManager abstracts provider-specific WebSocket management.
// This interface handles WebSocket connection lifecycle and log streaming.
type WebSocketManager interface {
	// HandleRequest processes WebSocket lifecycle events (connect, disconnect, etc.).
	// Returns true if the event was handled, false otherwise.
	HandleRequest(ctx context.Context, rawEvent *json.RawMessage, reqLogger *slog.Logger) (bool, error)

	// NotifyExecutionCompletion sends disconnect notifications to all connected clients for an execution
	// and removes the connections.
	NotifyExecutionCompletion(ctx context.Context, executionID *string) error

	// SendLogsToExecution flushes buffered log events to all connected clients for an execution.
	SendLogsToExecution(ctx context.Context, executionID *string) error

	// GenerateWebSocketURL creates a WebSocket token and returns the connection URL.
	// It stores the token for validation when the client connects.
	// Returns an empty string if URL generation fails (errors are logged).
	GenerateWebSocketURL(
		ctx context.Context,
		executionID string,
		userEmail *string,
		clientIPAtCreationTime *string,
	) string
}

// HealthManager abstracts provider-specific health checks and resource reconciliation.
// This interface handles verifying and repairing inconsistencies between metadata storage and cloud resources.
type HealthManager interface {
	// Reconcile checks and repairs inconsistencies between metadata storage and actual cloud resources.
	// It verifies compute resources (e.g., task definitions, containers), secrets, and identity/access resources.
	// Returns a comprehensive health report with all issues found and actions taken.
	Reconcile(ctx context.Context) (*api.HealthReport, error)
}
